# Generated by Django 3.1 on 2020-08-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='', max_length=50)),
                ('dataset_title', models.CharField(default='', max_length=50)),
                ('dataset_description', models.TextField(default='')),
                ('dataset_provider', models.CharField(default='', max_length=50)),
                ('dataset_date_creation', models.DateTimeField(auto_now_add=True)),
                ('dataset_date_update', models.DateTimeField(auto_now=True)),
                ('dataset_django_model', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_var_obj_name', models.CharField(default='', max_length=50)),
                ('test_var_obj_title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(default='', max_length=50)),
                ('var_title', models.CharField(default='', max_length=50)),
                ('var_category', models.CharField(default='', max_length=50)),
                ('var_definition', models.TextField(default='')),
                ('var_unit', models.CharField(default='', max_length=50)),
                ('variable_table_name', models.CharField(max_length=50, null=True)),
                ('dataset_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='TestDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=50)),
                ('test_var_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.testvariable')),
            ],
        ),
    ]
